// aige-frontend/src/App.js
import React, { useState } from 'react';
import './App.css'; // Make sure this file exists or is created
import Step1Avatar from './components/Step1Avatar';
import Step2Background from './components/Step2Background';
import TaskStatus from './components/TaskStatus';

function App() {
  const [avatarDetails, setAvatarDetails] = useState({
    id: null, // This is the avatar_id generated by Step1Avatar client-side
    aigeTaskId: null,
    readUrl: null, // readUrl for the avatar image itself
  });

  const [backgroundDetails, setBackgroundDetails] = useState({
    aigeTaskId: null,
    readUrl: null, // readUrl for the background image
  });

  const handleAvatarSuccess = ({ avatarId, aigeTaskId, readUrl }) => {
    setAvatarDetails({ id: avatarId, aigeTaskId: aigeTaskId, readUrl: readUrl });
    // Reset background details if a new avatar is generated
    setBackgroundDetails({ aigeTaskId: null, readUrl: null });
  };

  const handleBackgroundSuccess = ({ aigeTaskId, readUrl }) => {
    setBackgroundDetails({ aigeTaskId: aigeTaskId, readUrl: readUrl });
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>AIGE Frontend API Tester</h1>
      </header>
      <main className="App-main">
        <section className="step-section">
          <Step1Avatar onAvatarSuccess={handleAvatarSuccess} />
          {avatarDetails.aigeTaskId && (
            <TaskStatus
              aigeTaskId={avatarDetails.aigeTaskId}
              label="Avatar Generation Status"
            />
          )}
        </section>

        {/* Conditionally render Step 2 only if an avatar has been initiated */}
        {avatarDetails.id && (
          <section className="step-section">
            <Step2Background
              avatarId={avatarDetails.id}
              onBackgroundSuccess={handleBackgroundSuccess}
            />
            {backgroundDetails.aigeTaskId && (
              <TaskStatus
                aigeTaskId={backgroundDetails.aigeTaskId}
                label="Background Generation Status"
              />
            )}
          </section>
        )}
      </main>
      <footer className="App-footer">
        <p>AIGE Test Frontend</p>
        {/* This is a good place to show combined results or global errors if any */}
      </footer>
    </div>
  );
}

export default App;
